networks:
  <name_of_docker_network>:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=5881
    volumes:
      - <path_to_config_file>:/config
      - <path_to_files>:/tvseries
    ports:
      - 8080:8080
      - 5881:5881
      - 5881:5881/udp
    restart: unless-stopped
    networks:
      - <name_of_docker_network>