networks:
  <name_of_docker_network>:
    external: true

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - <path_to_config_file>:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - <name_of_docker_network>